import {Inter} from 'next/font/google';
import React from 'react';

const inter = Inter({subsets: ['latin']});

export const metadata = {
	title: 'TypeScript | About',
	description: 'Generated by create next app',
};

export default function Layout({children}: {children: React.ReactNode}) {
	return (
		<html lang='es'>
			<body className={inter.className}>
				{children}
			</body>
		</html>
	);
}

